### ISSUE TITLE
[TODO] Support padding in CONV and POOL

### ISSUE THREAD

**Issue by kumasento** [kumasento/maxdeep#13]
We need to support padding in CONV and POOL.

For `CONV`, the implementation would contain the following steps:
- [ ] Add padding parameter in `ConvLayerParameters`
- [ ] Revise the height and width counter in `ConvLayerKernel.maxj` to use
padded `H` and `W` as their max wrap point.
- [ ] Revise the condition to take input value from `ifmap` in `ConvLayerKernel.maxj` -
only takes input when `h` and `w` are out of the padding range.
- [ ] Add a mux to the input of line buffer - use `0` if `h` or `w` is in the padding range.
- [ ] Revise the calculation for OH and OW
- [ ] Add a test case

> We may not need `POOL` padding for now.
