### ISSUE TITLE
[TODO] An example manager of implementing VGG16

### ISSUE THREAD

**Issue by kumasento** [kumasento/maxdeep#15]
This is a quite hard objective and it has the following phases to complete.

### Confirm Layer Availability

I need to make sure that all parameters in VGG16 can be supported in `MaxDeep`.
- [ ] `CONV2D` can support padding
- [ ] `CONV2D` can read bias
- [ ] `FC` can read bias
- [ ] `ReLU` is an option that is available to `POOL` and `FC`.

**NOTE**: For now, I will not consider using dynamic values from scalar inputs
as the shape parameters of `CONV2D` or other layers.

(TBD)
